### ISSUE TITLE
contact info or discussion forum?

### ISSUE THREAD

**Issue by ktownsend-personal** [Retrotink/CHIP#1]
Not an issue with the project, but I haven't been able to figure out how to contact you. If there is a better channel please let me know. 

It was nice to meet you at VCF Southwest. I enjoyed building your kit over this past weekend and have just started tinkering with it.  I did some reading on the propeller chip to catch up on how this board works...pretty interesting architecture. I've been tinkering with ESP32 recently, which provided some good background to understand what makes the propeller chip so different. I particularly like how the VGA and probably a few other things each get a dedicated core to run truly parallel. I also like how that USB module really simplifies the power and serial interface in such a small package. I may borrow that approach for a [project I am working on](https://github.com/ktownsend-personal/RetroPhone) when I get to the point of making a board. 

I don't have a PS/2 keyboard laying around, but I found an [ESP32 project that acts as a Bluetooth to PS/2 adapter](https://github.com/Hamberthm/esp32-bt2ps2). It's pretty slick, and super simple to build because the PS/2 cable can be wired directly to the ESP32 without a level shifter if you're comfortable with relying on the GPIO having 5V input tolerance and the host accepts 3.3V logic high.  The maintainer has been very responsive with a keyboard protocol issue I happen to have with my keyboard. I'm currently operating with a temporary workaround until he properly fixes the protocol handling and it's been working great on the CHIP. I'm looking forward to poking around on the CHIP a bit more to see what it can do.

**Comment by Retrotink** [comment]
Sorry for the late response, I just found your post. You can reach m3 at vbriel@yahoo.com

**Comment by ktownsend-personal** [comment]
No worries! I figured you would see it eventually :) 
I'll send an email shortly.
